### ISSUE TITLE
캐릭터 정보를 찾을 수 없습니다 업데이트

### ISSUE THREAD

**Issue by Seojeonguk** [Jisup/maple_spy#3]
캐릭터 정보를 찾을 수 없다고 적혀 있는데 개인 장비나 이 외 정보는 가져오는 것 같습니다.

![KakaoTalk_20240321_144357914_03](https://github.com/Jisup/maple_spy/assets/44386047/f97ed486-5ba9-4d14-89c9-c60e211798a4)
![KakaoTalk_20240321_144357914](https://github.com/Jisup/maple_spy/assets/44386047/e370a087-096e-421c-84c9-28b6aac4f774)
![KakaoTalk_20240321_144357914_01](https://github.com/Jisup/maple_spy/assets/44386047/e3cc4026-e2a6-4fff-87fd-dfd3b7ea8ec4)
![KakaoTalk_20240321_144357914_02](https://github.com/Jisup/maple_spy/assets/44386047/90e25bd2-d68c-4a9c-b034-961fa1195ed3)

**Comment by Jisup** [comment]
스탯 데이터 전처리 과정 중 발생한 문제를 해결하였습니다.

특정 캐릭터의 경우 스탯 데이터 값 중 null이 포함되어 있었습니다. (ex: 제로)
